#!/bin/bash
#
# Code shared between the download & update script.
#
# Copyright (C) 2025  David Hobach  GPLv3
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 

set -o pipefail

#error [message]
function error {
>&2 echo "ERROR: $1"
>&2 echo "Aborting..."
exit 1
}

#getFirefoxProfileDir []
#returns: The firefox profile directory path.
function getFirefoxProfileDir {
local profIni=
profIni="$(find /home/ -path '*.mozilla/firefox/profiles.ini')" || error "Failed to find the profile directory."
[ -z "$profIni" ] && error "No profile directory found."
sed -rn 's/^Path=(.*)$/\1/p' "$profIni" || error "Failed to extract the profile directory."
}

#deps [dependency 1] ... [dependency n]
#Assert that the given dependencies are met and error out otherwise.
#This function is meant to be used by modules or scripts to declare all of their dependencies.
#[dependency i]: Command that is absolutely required to run this script.
#returns: Nothing. Errors out, if dependencies are not met.
function deps {
local dep=
local unmet=""

for dep in "$@" ; do
	[ -z "$dep" ] && continue
	command -v "$dep" &> /dev/null || unmet="$dep"$'\n'"$unmet"
done

[ -z "$unmet" ] || error "The script requires the following commands, but they were not found:"$'\n'"$unmet"
}

function getRunningFirefoxVersion {
local ret=
ret="$(firefox -v)" || error "Failed to retrieve the currently running local firefox version."

echo "${ret##Mozilla Firefox }"
return 0
}

deps "find" "sed" "firefox"
